# Generated from kak-tree-sitter-config/default-config.toml — do not edit directly.
# Regenerate by running: cargo build
#
# Top-level faces fall back to "default"; load your colorscheme AFTER this file
# so that the colorscheme's definitions take precedence.

set-face global attribute default
set-face global comment default
set-face global comment_block comment
set-face global comment_line comment
set-face global comment_unused comment
set-face global constant default
set-face global constant_builtin constant
set-face global constant_builtin_boolean constant_builtin
set-face global constant_character constant
set-face global constant_character_escape constant_character
set-face global constant_macro constant
set-face global constant_numeric constant
set-face global constant_numeric_float constant_numeric
set-face global constant_numeric_integer constant_numeric
set-face global constructor default
set-face global diff_delta diff
set-face global diff_delta_moved diff_delta
set-face global diff_minus diff
set-face global diff_plus diff
set-face global embedded default
set-face global error default
set-face global function default
set-face global function_builtin function
set-face global function_macro function
set-face global function_method function
set-face global function_method_private function_method
set-face global function_special function
set-face global hint default
set-face global include default
set-face global info default
set-face global keyword default
set-face global keyword_conditional keyword
set-face global keyword_control keyword
set-face global keyword_control_conditional keyword_control
set-face global keyword_control_except keyword_control
set-face global keyword_control_exception keyword_control
set-face global keyword_control_import keyword_control
set-face global keyword_control_repeat keyword_control
set-face global keyword_control_return keyword_control
set-face global keyword_directive keyword
set-face global keyword_function keyword
set-face global keyword_operator keyword
set-face global keyword_special keyword
set-face global keyword_storage keyword
set-face global keyword_storage_modifier keyword_storage
set-face global keyword_storage_modifier_mut keyword_storage_modifier
set-face global keyword_storage_modifier_ref keyword_storage_modifier
set-face global keyword_storage_type keyword_storage
set-face global label default
set-face global load default
set-face global markup_bold markup
set-face global markup_heading markup
set-face global markup_heading_1 markup_heading
set-face global markup_heading_2 markup_heading
set-face global markup_heading_3 markup_heading
set-face global markup_heading_4 markup_heading
set-face global markup_heading_5 markup_heading
set-face global markup_heading_6 markup_heading
set-face global markup_heading_marker markup_heading
set-face global markup_italic markup
set-face global markup_link_label markup_link
set-face global markup_link_text markup_link
set-face global markup_link_uri markup_link
set-face global markup_link_url markup_link
set-face global markup_list_checked markup_list
set-face global markup_list_numbered markup_list
set-face global markup_list_unchecked markup_list
set-face global markup_list_unnumbered markup_list
set-face global markup_quote markup
set-face global markup_raw markup
set-face global markup_raw_block markup_raw
set-face global markup_raw_inline markup_raw
set-face global markup_strikethrough markup
set-face global namespace default
set-face global operator default
set-face global punctuation default
set-face global punctuation_bracket punctuation
set-face global punctuation_delimiter punctuation
set-face global punctuation_special punctuation
set-face global special default
set-face global string default
set-face global string_escape string
set-face global string_regexp string
set-face global string_special string
set-face global string_special_path string_special
set-face global string_special_symbol string_special
set-face global string_symbol string
set-face global tag default
set-face global tag_error tag
set-face global text default
set-face global type default
set-face global type_builtin type
set-face global type_enum_variant type_enum
set-face global type_enum_variant_builtin type_enum_variant
set-face global type_parameter type
set-face global variable default
set-face global variable_builtin variable
set-face global variable_other_member variable_other
set-face global variable_other_member_private variable_other_member
set-face global variable_parameter variable
set-face global warning default
